### ISSUE TITLE
About Color Map

### ISSUE THREAD

**Issue by liudixian** [keijiro/Abcvfx#1]
![屏幕截图 2021-02-04 175655](https://user-images.githubusercontent.com/11694349/106876238-78e0c200-6712-11eb-9630-a7f092a6e2f3.png)
![屏幕截图 2021-02-04 175733](https://user-images.githubusercontent.com/11694349/106876242-7a11ef00-6712-11eb-83f6-486606171c12.png)

Hi, I noticed that the normal information doesn't seem to be correct, is this a bug in the current implementation?

**Comment by keijiro** [comment]
Could you provide a minimal project that reproduces the issue?

**Comment by liudixian** [comment]
Thank you for your patience, the file is in this location : https://drive.google.com/drive/folders/1mVpAC1oXu5Wi_h5ODqeQ_keQhQCUq2o7?usp=sharing

**Comment by keijiro** [comment]
Thanks for providing the project. I think you should use a graph like this to check normals:
![image](https://user-images.githubusercontent.com/343936/106902612-5fed0680-673c-11eb-8cd5-3d91099157b4.png)

**Comment by keijiro** [comment]
I checked the normals using the graph above and concluded that they're correctly imported.

I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by liudixian** [comment]
Hi, Thank you very much for the correction, I really didn't understand the sampling method before. Just now I borrowed it's sampling method to read the information of color and other maps by looking at your kinect point cloud case.But when I look at the color, I have a new problem, it seems that the index of the color point is not consistent with the position index. I am not sure what the problem is now?

![map](https://user-images.githubusercontent.com/11694349/107001542-c61d6c00-67c4-11eb-9ac9-7bbcbd832cff.png)
![bug](https://user-images.githubusercontent.com/11694349/107001545-c7e72f80-67c4-11eb-9d80-b74badb56bfb.png)

**Comment by keijiro** [comment]
Could you provide this project too?

**Comment by liudixian** [comment]
Of course, this is the link: https://drive.google.com/drive/folders/1ec-I9l4OmloHR0VOGmI2XVTE2HQwvuxw?usp=sharing.

**Comment by keijiro** [comment]
Thanks for sharing the project.

I found an issue with UV coordinate calculation. Could you try changing this line:

https://github.com/keijiro/Abcvfx/blob/master/Packages/jp.keijiro.abcvfx/Resources/MeshToPoints.compute#L59

```
uint2 sp = float2(uvc.x, 1 - uvc.y) * uint2(tw, th) + 0.5;
```

as following? (just removing `1 - ` term)

```
uint2 sp = float2(uvc.x, uvc.y) * uint2(tw, th) + 0.5;
```

**Comment by liudixian** [comment]
Cool, now is perfect! Thank you !

**Comment by keijiro** [comment]
This `1 - ` term is needed when using a HAP video as a texture stream. I usually use Alembic with HAP, so I didn't notice the problem.

I'll add a switch to change this behavior. Until then, please use the modified code.

**Comment by liudixian** [comment]
ok, thanks!
