### ISSUE TITLE
The type or namespace'Collider' could not be found...

### ISSUE THREAD

**Issue by jBachalo** [keijiro/Abcvfx#3]
Just opening the project in Unity 2019.4.18f1 getting many errors

Library\PackageCache\com.unity.render-pipelines.core@7.4.1\Runtime\Volume\VolumeManager.cs(55,23): error CS0246: The type or namespace name 'Collider' could not be found 

The type or namespace name 'ParticleSystem' could not be found (are you missing a using directive or an assembly reference?)

The type name 'PlayableDirector' could not be found in the namespace 'UnityEngine.Playables'. This type has been forwarded to assembly 'UnityEngine.DirectorModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

Are there packages that need to be opened in Package Manager?

**Comment by keijiro** [comment]
Maybe yes. Please try adding those built-in packages from the Package Manager UI.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by jBachalo** [comment]
Thanks for the quick feedback. Still unclear exactly which packages I need to add. ie There is no Particlesystem or PlayableDirector package AFAIK. I tried upgrading both VFX graph and Alembic packages but still get same errors.

**Comment by keijiro** [comment]
It says Collider is missing so Physics might be needed.

**Comment by jBachalo** [comment]
So issue is resolved. The project is tagged with an older version of Unity 2019.4.3
But if I launch using v2021 there are no issues.
